# Generated by Django 3.0.3 on 2020-05-12 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True)),
                ('bookmass_time', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('fullname', models.CharField(max_length=200)),
                ('mobile_no', models.CharField(max_length=50)),
                ('names_to_pray_for', models.TextField(blank=True)),
                ('intention', models.TextField(blank=True)),
                ('intention_category', models.CharField(max_length=200)),
                ('intention_start_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('intention_end_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('amount_paid', models.CharField(max_length=50)),
                ('have_open_thanksgiving', models.BooleanField(default=False)),
                ('thanksgiving_day', models.CharField(blank=True, max_length=50)),
                ('thanksgiving_time', models.CharField(blank=True, max_length=50)),
                ('photo_pay_evidence', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('create_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
