# Generated by Django 3.0.3 on 2020-05-12 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baptism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True)),
                ('bap_first_name', models.CharField(max_length=50)),
                ('bap_middle_name', models.CharField(max_length=50)),
                ('bap_last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.CharField(max_length=50)),
                ('place_of_birth', models.CharField(max_length=50)),
                ('home_town', models.CharField(max_length=50)),
                ('state_origin', models.CharField(max_length=50)),
                ('adult_mobile_no', models.CharField(max_length=50)),
                ('fathers_name', models.CharField(max_length=50)),
                ('fathers_mobile_no', models.CharField(max_length=50)),
                ('mothers_name', models.CharField(max_length=50)),
                ('mothers_mobile_no', models.CharField(max_length=50)),
                ('parents_address', models.TextField(blank=True)),
                ('parents_marital_status', models.CharField(max_length=50)),
                ('parents_marriage_parish', models.CharField(max_length=200)),
                ('god_fathers_name', models.CharField(max_length=50)),
                ('god_fathers_mobile_no', models.CharField(max_length=50)),
                ('god_fathers_address', models.TextField(blank=True)),
                ('god_mothers_name', models.CharField(max_length=50)),
                ('god_mothers_mobile_no', models.CharField(max_length=50)),
                ('god_mothers_address', models.TextField(blank=True)),
                ('digital_signature', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('create_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
